#!/bin/bash

# Install 'git'
pacman -Qi git 1>/dev/null 2>/dev/null || sudo pacman -S --noconfirm --needed git

# Install 'yay'
    # Check whether 'yay' has been installed
pacman -Qi yay 1>/dev/null 2>/dev/null
if [ $? -ne 0 ]
then
    pacman -Qi base-devel 1>/dev/null 2>/dev/null || sudo pacman -S --noconfirm --needed base-devel
    git clone -- https://aur.archlinux.org/yay.git /tmp/yay
    pushd /tmp/yay
    makepkg -si
    popd
fi

DOTFILES_DIRNAME=.setup
DOTFILES_PATH=~/${DOTFILES_DIRNAME}
# Clone the dotfiles into ${DOTFILES_PATH}
if [ ! -d ${DOTFILES_PATH} ]
then
    git clone -- ssh://chris85618@chris85618.diskstation.me:29998/chris85618/Dotfiles.git ${DOTFILES_PATH}
fi

read -p '''Please enable multilib first, and then just click the Enter key once: https://wiki.archlinux.org/title/Official_repositories#multilib
'''

cat ${DOTFILES_PATH}/pacman_requirements.txt | yay -Syy --needed --noconfirm -

# Enable the dotfile@home
link_dirname="${DOTFILES_PATH}/configs/home"
for file in $(find ${link_dirname} -type d)
do
    mkdir -p $(echo ${file} | sed "s:${link_dirname}:${HOME}:g")
done
for file in $(find ${link_dirname} -type f ! -name .gitkeep)
do
    filepath="$(echo ${file} | sed "s:${HOME}:~:g")"
    linkpath="$(echo ${file} | sed "s:${link_dirname}:${HOME}:g")"
    ln -is ${file} ${linkpath}
done
unset file
unset link_dirname
unset linkpath
unset DOTFILES_DIRNAME
unset DOTFILES_PATH
